"""remove

Revision ID: e29861c9f20c
Revises: 5176bcfe9e97
Create Date: 2026-01-19 12:00:37.728300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29861c9f20c'
down_revision: Union[str, Sequence[str], None] = '5176bcfe9e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
